# Generated by Django 5.0.3 on 2024-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_order_prise_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_products',
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(to='myapp.product'),
        ),
    ]
