# Generated by Django 5.0.3 on 2024-03-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_order_order_products_order_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_products',
            new_name='products',
        ),
    ]
