# Generated by Django 5.0.3 on 2024-03-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=120)),
                ('client_registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=120)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_amount', models.IntegerField()),
                ('product_added_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_prise', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_date', models.DateField()),
                ('order_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.client')),
                ('order_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.product')),
            ],
        ),
    ]
